name: Atualizar estatísticas do README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v6

      - name: Gerar estatísticas
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: "username=${{ github.repository_owner }}&show_icons=true&hide_border=false&border_radius=16&border_color=2383d9&title_color=58a6ff&icon_color=2f81f7&text_color=c9d1d9&bg_color=0d1117&include_all_commits=true"
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gerar linguagens mais utilizadas
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: "username=${{ github.repository_owner }}&layout=compact&langs_count=6&hide_border=false&border_radius=16&border_color=6e5ce7&title_color=a371f7&text_color=c9d1d9&bg_color=0d1117"
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Salvar estatísticas
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Atualizar estatísticas do README" || exit 0
          git push
